#### Roche Nimblegen data analysis example
# Create working environment
homedir <- getwd()
setwd(homedir)
options(java.parameters = "-Xmx8G")
library(BiocParallel)
library(EnhancedVolcano)
library(enrichR)
library(fgsea)
library(gplots)
library(ggplot2)
library(limma)
library(magrittr)
library(msigdbr)
library(pheatmap)
library(stringr)
require(vulcan)
library(xlsx)
register(SnowParam(12))
